default_language_version:
  python: python3.11
exclude: '^\.internal/docs/.*' # exclude docs from pre-commit hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.4
    hooks:
      - id: nbqa-isort

  - repo: local
    hooks:
      - id: upgrade-nbformat
        name: Upgrade notebooks nbformat
        entry: .internal/pre_commit_tools/set_nbformat.py
        language: python
        files: ^\S+\.ipynb$
        additional_dependencies:
          - "nbformat"
        require_serial: true
      - id: extra-nbstripout
        name: Strip further stuff from notebooks
        entry: .internal/pre_commit_tools/extra_nbstripout.py
        language: python
        files: ^\S+\.ipynb$
        additional_dependencies:
          - "nbformat"
        require_serial: true

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        args:
          [
            --keep-output,
            --keep-count,
            --drop-empty-cells,
            --keep-metadata-keys=cell.metadata.scrolled,
          ]

  - repo: local
    hooks:
      - id: notebook-pre-commit
        name: Notebook pre commit collection
        description: Ensure notebooks conventions
        entry: .internal/pre_commit_tools/notebook_pre_commit_collection.py
        language: python
        files: ^\S+\.ipynb$
        additional_dependencies:
          - "pyyaml==6.0"
        require_serial: true
      - id: qmod-pre-commit
        name: Qmod pre commit collection
        description: Ensure qmods conventions
        entry: .internal/pre_commit_tools/qmod_pre_commit_collection.py
        language: python
        files: ^\S+\.qmod$
        additional_dependencies:
          - "pyyaml==6.0"
        require_serial: true
      - id: clean-demo-timeouts
        name: Clean demo timeouts
        description: Remove unexisting entries and verify unique keys
        entry: .internal/pre_commit_tools/clean_timeouts.py
        language: python
        files: ^\S+\.(qmod|ipynb|yaml)$
        additional_dependencies:
          - "pyyaml==6.0"
        require_serial: true
      - id: auto-add-tests
        name: Auto add test
        description: Automatically adding a test to new notebooks
        entry: .internal/pre_commit_tools/auto_add_tests.py
        language: python
        files: ^\S+\.ipynb$
        require_serial: true
