name: "Automatic Deployment"

on:
  pull_request_target:
    branches:
      - main
      - dev
    types:
      - closed

jobs:
  deploy-prod:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/deployment-qmod.yml
    with:
      deploy-mode: production
    secrets: inherit

  deploy-dev:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
    uses: ./.github/workflows/deployment-qmod.yml
    with:
      deploy-mode: staging
    secrets: inherit
